#!/bin/bash
##Only for sles15sp2 OS
##Created by Georgy D
##Create Local user
dir=/etc/pam.d

echo "Enter groupname:"
read group
echo "Enter username:"
read user
echo "Enter gid:"
read gid
echo "Enter uid:"
read uid

groupadd --gid ${gid} ${group}

useradd --uid ${uid} -g ${group} ${user}

cd $dir 

cp common-account.pam-config-backup common-account
cp common-auth.pam-config-backup common-auth
cp common-password.pam-config-backup common-password
cp common-session.pam-config-backup common-session
passwd ${user}

cp common-account-pc common-account
cp common-auth-pc common-auth
cp common-password-pc common-password
cp common-session-pc common-session
